travis:
  secure:
    BINSTAR_TOKEN: o/9/dn0maBwTFIcLS597J/wasxzprV5DnOdPPWFtsj0zdVjW4hkr2JvJdjO7BX9KTySffoAGnekKdGk6k7n+Tk00VWdaZE2EGb6cCi5vibPAZgpVhpQyU4jq6IUbPJ8fQiiiQX57HpBm/8fV87ljTY+C/bnd+KKorGqCrbPWxwce/c51UVkF7MzlNAF6u+VA164zQRtOWzhBs0PRt6Huhwd5IBIOxYcnn6Lo6aTGz2e0O7lrQesm4IVsXXtUtVTrDqdOZ6YmRX+Ak9oisE0yPNv/oTmpdffo5AfLbppIpL2kywkpfL0tzfSCISjnWL0f1L077wAThha2UaVPeBBxwQXkORP83B/mUvM6CG3CO66Ke9YnJcpbPhp+j7K79CRQ3uc+nylUqqzeQqJSy140+2BmlrXMsqQj1aueSpAto+laKvBlFLzZsNoX7dYWKBh0dZSgzzSLOruvvXaw8RWnzV3UFAupgczYAww4dAMVjFsdPAEGjmtdh4S2ZFP5RDPFzmqElcTr6O/1QI7+ljnco3hyum3rwmB+uMmq5pRxkCewnIKWVOstFSU9SZHPn+Bbx1c2aBrhUjsd8ihh8Rv41DuzOOC/OYK/0UcmhIJ2hv5j1Cf9xRas5FzQNr1gwKlp0Cd2ukY9qD1DvAvDB3sZKWOGTD08jS26WqGU+a6cjcw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
